[package]
name = "MyDAO"
version = "1.0.0"
authors = ["dApp Builder"]

[addresses]
dao_owner = "0x0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
